#!/bin/sh

if ! OPTS=$(getopt -o 'ho:' --long 'help,options:' -n 'dotfiles.setup' -- "$@"); then
  echo 'Terminating...' >&2
  exit 1
fi

eval set -- "$OPTS"
unset OPTS

ANDROID=false
VIM=false
ZSH=false

while true; do
  case "$1" in
    '-h'|'--help')
      cat << EOF
Usage: setup [OPTION...]

 Dotfile setup selection:

  -o,   --options=OPTS       

 Valid OPTS are:

    setup=dotfile1[:dotfile2] A list of dotfiles to set up seperated by :
    android                   If setup should config for android

 Other options:

  -h, --help                  Give this help list

Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
EOF
    exit
    ;;
    '-o'|'--options')
      IFS="," for opt in $2; do
        case "$opt" in
          'android')
            ANDROID=true
          ;;
          setup=*)
            echo "$opt"
          ;;
          *)
            echo "Unkown option '$opt'" >&2
            exit 1
          ;;
        esac
      done
      shift 2
      continue
    ;;
    '--')
      shift
      break
    ;;
    *)
      echo 'Internal error!' >&2
      exit 1
    ;;
  esac
done

echo 'Remaining arguments:'
for arg; do
  echo "--> '$arg'"
done

unset ANDROID VIM ZSH

# vim: set ft=sh
