#!/usr/bin/env zsh
# shellcheck shell=bash

# check arguments count
if (( ${#@} - 1 )); then
  print 'Usage: sudoedit FILE'
  exit 1
fi

# check if a file was passed as argument
 


# vim: set ft=zsh ts=2 sw=2 sts=2 et nu fenc=utf-8:
